apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:${{IMAGE_TAG}}
        ports:
        - containerPort: 8000
