apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: XXXXXXXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:initial
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      imagePullSecrets:
      - name: ecr-pull-secret
