apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: xxxxxxxxxxxxxxxxx.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:initial
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        
        volumeMounts:
        - name: logs-volume
          mountPath: /githubactions/src/logs
     
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      imagePullSecrets:
      - name: ecr-pull-secret
      
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: fastapi-logs-pvc
      
